# Generated by Django 2.2 on 2020-09-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200927_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
